package com.poem.entity;

public class one_article_a_day {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_article_a_day.id
     *
     * @mbggenerated Mon Apr 13 20:25:16 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_article_a_day.article
     *
     * @mbggenerated Mon Apr 13 20:25:16 CST 2020
     */
    private String article;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_article_a_day.id
     *
     * @return the value of one_article_a_day.id
     *
     * @mbggenerated Mon Apr 13 20:25:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_article_a_day.id
     *
     * @param id the value for one_article_a_day.id
     *
     * @mbggenerated Mon Apr 13 20:25:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_article_a_day.article
     *
     * @return the value of one_article_a_day.article
     *
     * @mbggenerated Mon Apr 13 20:25:16 CST 2020
     */
    public String getArticle() {
        return article;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_article_a_day.article
     *
     * @param article the value for one_article_a_day.article
     *
     * @mbggenerated Mon Apr 13 20:25:16 CST 2020
     */
    public void setArticle(String article) {
        this.article = article;
    }
}