package com.poem.entity;

import java.util.ArrayList;
import java.util.List;

public class poem_sortExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public poem_sortExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameIsNull() {
            addCriterion("poemsort_name is null");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameIsNotNull() {
            addCriterion("poemsort_name is not null");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameEqualTo(String value) {
            addCriterion("poemsort_name =", value, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameNotEqualTo(String value) {
            addCriterion("poemsort_name <>", value, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameGreaterThan(String value) {
            addCriterion("poemsort_name >", value, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameGreaterThanOrEqualTo(String value) {
            addCriterion("poemsort_name >=", value, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameLessThan(String value) {
            addCriterion("poemsort_name <", value, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameLessThanOrEqualTo(String value) {
            addCriterion("poemsort_name <=", value, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameLike(String value) {
            addCriterion("poemsort_name like", value, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameNotLike(String value) {
            addCriterion("poemsort_name not like", value, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameIn(List<String> values) {
            addCriterion("poemsort_name in", values, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameNotIn(List<String> values) {
            addCriterion("poemsort_name not in", values, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameBetween(String value1, String value2) {
            addCriterion("poemsort_name between", value1, value2, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andPoemsortNameNotBetween(String value1, String value2) {
            addCriterion("poemsort_name not between", value1, value2, "poemsortName");
            return (Criteria) this;
        }

        public Criteria andSortRemarkIsNull() {
            addCriterion("sort_remark is null");
            return (Criteria) this;
        }

        public Criteria andSortRemarkIsNotNull() {
            addCriterion("sort_remark is not null");
            return (Criteria) this;
        }

        public Criteria andSortRemarkEqualTo(String value) {
            addCriterion("sort_remark =", value, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkNotEqualTo(String value) {
            addCriterion("sort_remark <>", value, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkGreaterThan(String value) {
            addCriterion("sort_remark >", value, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("sort_remark >=", value, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkLessThan(String value) {
            addCriterion("sort_remark <", value, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkLessThanOrEqualTo(String value) {
            addCriterion("sort_remark <=", value, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkLike(String value) {
            addCriterion("sort_remark like", value, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkNotLike(String value) {
            addCriterion("sort_remark not like", value, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkIn(List<String> values) {
            addCriterion("sort_remark in", values, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkNotIn(List<String> values) {
            addCriterion("sort_remark not in", values, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkBetween(String value1, String value2) {
            addCriterion("sort_remark between", value1, value2, "sortRemark");
            return (Criteria) this;
        }

        public Criteria andSortRemarkNotBetween(String value1, String value2) {
            addCriterion("sort_remark not between", value1, value2, "sortRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table poem_sort
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 13 20:27:54 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table poem_sort
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}