package com.poem.entity;

public class poem_sort {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poem_sort.id
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poem_sort.poemsort_name
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    private String poemsortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poem_sort.sort_remark
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    private String sortRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poem_sort.id
     *
     * @return the value of poem_sort.id
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poem_sort.id
     *
     * @param id the value for poem_sort.id
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poem_sort.poemsort_name
     *
     * @return the value of poem_sort.poemsort_name
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public String getPoemsortName() {
        return poemsortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poem_sort.poemsort_name
     *
     * @param poemsortName the value for poem_sort.poemsort_name
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public void setPoemsortName(String poemsortName) {
        this.poemsortName = poemsortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poem_sort.sort_remark
     *
     * @return the value of poem_sort.sort_remark
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public String getSortRemark() {
        return sortRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poem_sort.sort_remark
     *
     * @param sortRemark the value for poem_sort.sort_remark
     *
     * @mbggenerated Mon Apr 13 20:27:54 CST 2020
     */
    public void setSortRemark(String sortRemark) {
        this.sortRemark = sortRemark;
    }
}